apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../tumblebug-web-app/overlays/data-studio
- ../../automlab-web-app/overlays/data-studio
- ../../mole-web-app/overlays/data-studio
- ../../whale-web-app/overlays/data-studio
- ./serviceAccount.yaml

namespace: kubeflow
labels:
- includeSelectors: true
  pairs:
    DataStudio.component: lab-product-gui
