apiVersion: v1
data:
  notebook_template.yaml: |
    apiVersion: kubeflow.org/v1beta1
    kind: Notebook
    metadata:
      name: {name}
      namespace: "{namespace}"
      labels:
        app: {name}
      annotations:
        notebooks.kubeflow.org/server-type: ""
    spec:
      template:
        spec:
          serviceAccountName: {serviceAccount}
          containers:
            - name: {name}
              image: ""
              volumeMounts:
                - mountPath: /var/run/secrets/kubeflow/pipelines
                  name: volume-kf-pipeline-token
                  readOnly: true
              env:
                - name: KF_PIPELINES_SA_TOKEN_PATH
                  value: /var/run/secrets/kubeflow/pipelines/token
              resources:
                requests:
                  cpu: "0.1"
                  memory: "0.1Gi"
          securityContext:
            fsGroup: 1000
          volumes:
            - name: volume-kf-pipeline-token
              projected:
                sources:
                  - serviceAccountToken:
                      path: token
                      expirationSeconds: 86400
                      audience: pipelines.kubeflow.org
          tolerations: []
kind: ConfigMap
metadata:
  name: datastudio-notebook-template
  namespace: kubeflow