apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Cert-Manager
  - ../common/cert-manager/cert-manager/base
  - ../common/cert-manager/kubeflow-issuer/base
  # Istio
  # - ../common/istio-1-22/istio-crds/base
  # - ../common/istio-1-22/istio-namespace/base
  # - ../common/istio-1-22/istio-install/overlays/oauth2-proxy
  - ../common/istio-cni-1-22/istio-crds/base
  - ../common/istio-cni-1-22/istio-namespace/base
  - ../common/istio-cni-1-22/istio-install/overlays/oauth2-proxy
  # oauth2-proxy
  - ../common/oidc-client/oauth2-proxy/overlays/m2m-self-signed
  # Dex
  - ../common/dex/overlays/oauth2-proxy
  # Kubeflow namespace
  - ../common/kubeflow-namespace/base
  # NetworkPolicies
  - ../common/networkpolicies/base
  # Kubeflow Roles
  - ../common/kubeflow-roles/base
  # Kubeflow Istio Resources
  # - ../common/istio-1-22/kubeflow-istio-resources/base
  - ../common/istio-cni-1-22/kubeflow-istio-resources/base

  # Kubeflow Pipelines
  - ../apps/pipeline/upstream/env/cert-manager/platform-agnostic-multi-user
  # Central Dashboard
  - ../apps/centraldashboard/upstream/overlays/oauth2-proxy
  # Admission Webhook
  - ../apps/admission-webhook/upstream/overlays/cert-manager
  # Jupyter Web App
  - ../apps/jupyter/jupyter-web-app/upstream/overlays/istio
  # Notebook Controller
  - ../apps/jupyter/notebook-controller/upstream/overlays/kubeflow
  # Profiles + KFAM
  - ../apps/profiles/upstream/overlays/kubeflow
  # PVC Viewer
  - ../apps/pvcviewer-controller/upstream/base
  # Volumes Web App
  - ../apps/volumes-web-app/upstream/overlays/istio
  # User namespace
  - ../common/user-namespace/base

  # OpenShift Specific Patches
  # SCC / RBAC
  - ./istio-cni-1-22-patches/istio-sidecar-with-pvc.yaml
  - ./istio-1-22-patches/scc-istiod-sidecar-proxy-reserved.yaml
  - ./minio-related/minio-sa.yaml
  - ./minio-related/minio-sa-scc-binding.yaml
  - ./mysql-related/mysql-anyuid-binding.yaml

# Pod Security Standards
# https://kubernetes.io/docs/concepts/security/pod-security-standards/
# Uncomment to enable baseline level standards
# - ../contrib/security/PSS/static/baseline
# Uncomment to enable restricted level standards
# - ../contrib/security/PSS/static/restricted

patches:
  - path: istio-cni-1-22-patches/istio-cni-node-patch.yaml
    target:
      kind: DaemonSet
      name: istio-cni-node
      namespace: kube-system
  - path: minio-related/minio-service-portname.yaml
    target:
      kind: Service
      name: minio-service
      namespace: kubeflow
  # 放寬 ML Pipeline 的啟動探針時間
  - path: pipeline-related/ml-pipeline-startup-probe.yaml # 可選
    target:
      kind: Deployment
      name: ml-pipeline
      namespace: kubeflow
  - path: minio-related/minio-inject-and-sa.yaml
    target: 
      kind: Deployment
      name: minio
      namespace: kubeflow
  - path: pipeline-related/ml-pipeline-inject.yaml
    target: 
      kind: Deployment
      name: ml-pipeline
      namespace: kubeflow
  - path: mysql-related/mysql-inject-and-sa.yaml # 若需要
    target: 
      kind: Deployment
      name: mysql
      namespace: kubeflow
