apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow

resources:
# for system:image-puller permission of kubeflow namespace
- roleBinding.yaml
# for DataStudio anyuid SCC
- securityContextConstraints.yaml