apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: data-studio-admin-clusterrolebinding-kfadmin
  labels:
    dataStudio: admin
subjects:
- kind: User
  name: kfadmin
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: data-studio-admin
  apiGroup: rbac.authorization.k8s.io
