apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: data-studio-admin
  namespace: kubeflow
  labels:
    dataStudio: admin
rules:
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["rolebindings"]
  verbs: ["get", "list", "create", "delete", "update"]
- apiGroups: ["image.openshift.io"]
  resources: ["imagestreams"]
  verbs: ["get", "list", "create", "delete", "update", "watch", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "create", "delete", "update", "watch", "patch"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["get", "list", "create", "delete", "update", "watch", "patch"]