# To Solve: 
# Invalid value: "hostPath": hostPath volumes are not allowed to be used
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: kubeflow
  name: kfp-csi-s3
spec:
  template:
    spec:
      volumes:
      - name: registration-dir
        hostPath:
          $patch: replace
          path: /var/data/kubelet/plugins_registry
          type: DirectoryOrCreate