apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../../../common/dex/overlays/istio

namespace: auth
labels:
- includeSelectors: true
  pairs:
    DataStudio.version: "0.9"

configMapGenerator:
- name: dex
  behavior: replace
  files:
  - config.yaml