apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline
  namespace: kubeflow
spec:
  template:
    spec:
      containers:
      - name: ml-pipeline-api-server
        startupProbe:
          exec:
            command: ["wget","-q","-S","-O","-","http://localhost:8888/apis/v1beta1/healthz"]
          timeoutSeconds: 5
          failureThreshold: 24