apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#namespace: istio-system
resources:
- ../../../../../../common/istio-1-16/istio-crds/base
- ../../../../../../common/istio-1-16/istio-namespace/base
- ../../../../../../common/istio-1-16/istio-install/base
- ../../../../../../common/istio-1-16/kubeflow-istio-resources/base
- ingressgateway.route.yaml