apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  annotations:
    serviceaccounts.openshift.io/oauth-redirecturi.dex: http://istio-ingressgateway-istio-system.apps-crc.testing/dex/callback