apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-pipelineloop-webhook-advance
  namespace: tekton-pipelines
subjects:
  - kind: ServiceAccount
    name: tekton-pipelineloop-webhook
    namespace: tekton-pipelines
roleRef:
  kind: ClusterRole
  name: tekton-pipelineloop-webhook-advance
  apiGroup: rbac.authorization.k8s.io