apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- clusterRoleBinding.yml
- clusterRole.yml
- roleBinding.yml
- role.yml

labels:
- includeSelectors: true
  pairs:
    DataStudio.version: "0.9"